"""Core nodes — OWNER: M1 (Graph Architect).

Do not edit this file if you are not M1.
"""

from __future__ import annotations

from .state import AgentState, make_event


def intake_node(state: AgentState) -> dict:
    """Normalize raw query. This node is provided as a working example."""
    query = state.get("query", "").strip()
    return {
        "query": query,
        "messages": [f"intake:{query[:40]}"],
        "events": [make_event("intake", "completed", "query normalized")],
    }


def finalize_node(state: AgentState) -> dict:
    """Emit a final audit event. All routes must pass through here before END.

    CONTRACT: event node name MUST be exactly "finalize" —
    tests/test_graph_smoke.py::test_graph_terminates_all_routes greps for it.

    Return: {"events": [make_event("finalize", "completed", "workflow finished")]}
    """
    return {"events": [make_event("finalize", "completed", "workflow finished")]}
