"""Answer generation nodes — OWNER: M3.

Do not edit this file if you are not M3.
"""

from __future__ import annotations

from .llm import get_llm
from .state import AgentState, make_event

ANSWER_SYSTEM = """You are a customer-support agent writing the final reply to a ticket.

Rules:
- Use ONLY facts present in the provided context (user query, tool results, approval).
- If a needed fact is missing from the context, say so explicitly — never invent IDs,
  order numbers, statuses, refund amounts, or email confirmations.
- Prefer short, clear, actionable prose.
- When tool results mention concrete values (e.g. order 12345), include those values
  in the reply so the customer can verify them.
"""

CLARIFY_SYSTEM = """You are a customer-support agent. The user's request is incomplete or was
blocked. Write ONE specific clarification question that would unblock the case.

Rules:
- Output exactly one question (you may add one short leading sentence if needed).
- Be concrete: ask for the missing detail (order id, account email, what "it" refers to, etc.).
- Do not invent facts. Do not greet. Do not apologize at length.
- If the request was rejected by a reviewer, mention the rejection reason and propose
  a safer alternative the user can choose.
"""


def _format_tool_results(tool_results: list[str] | None) -> str:
    if not tool_results:
        return "(none)"
    return "\n".join(f"- {item}" for item in tool_results)


def _format_approval(approval: dict | None) -> str:
    if not approval:
        return "(none)"
    approved = approval.get("approved")
    reviewer = approval.get("reviewer", "unknown")
    comment = approval.get("comment", "")
    return f"approved={approved}; reviewer={reviewer}; comment={comment}"


def _safe_text(text: str | None, fallback: str) -> str:
    cleaned = (text or "").strip()
    return cleaned if cleaned else fallback


def answer_node(state: AgentState) -> dict:
    """Generate a final response using an LLM.

    *** MUST use a real LLM call — hardcoded strings will lose points. ***

    Ground the response in available context: query, tool_results, approval.
    Prompt constraint: use only facts present in the context; if a fact is missing,
    say it is missing rather than inventing it.

    CONTRACT:
    - MUST NOT return "route" (would corrupt metric_from_state's route comparison).
    - "final_answer" must be non-empty.
    - Event node name MUST be "answer".

    Return: {"final_answer": str, "events": [make_event("answer", ...)]}
    """
    query = state.get("query", "")
    tool_results = list(state.get("tool_results") or [])
    approval = state.get("approval")

    user_prompt = (
        f"User query:\n{query}\n\n"
        f"Tool results:\n{_format_tool_results(tool_results)}\n\n"
        f"Approval:\n{_format_approval(approval if isinstance(approval, dict) else None)}\n\n"
        "Write the final customer-facing answer."
    )

    errors: list[str] = []
    try:
        llm = get_llm(temperature=0.0)
        response = llm.invoke(
            [
                {"role": "system", "content": ANSWER_SYSTEM},
                {"role": "user", "content": user_prompt},
            ]
        )
        raw = getattr(response, "content", response)
        if isinstance(raw, list):
            # Some providers return a list of content blocks.
            raw = " ".join(
                block.get("text", str(block)) if isinstance(block, dict) else str(block)
                for block in raw
            )
        final_answer = _safe_text(str(raw), "I do not have enough verified information to answer.")
    except Exception as exc:  # noqa: BLE001 — node must not raise
        errors.append(f"answer_node LLM failure: {exc}")
        # Grounded fallback: surface tool facts if any, otherwise admit missing info.
        if tool_results:
            final_answer = (
                "I could not generate a full reply, but here are the verified tool results:\n"
                + "\n".join(tool_results)
            )
        else:
            final_answer = (
                "I do not have enough verified information in context to answer this request."
            )

    result: dict = {
        "final_answer": final_answer,
        "events": [make_event("answer", "completed", "final answer generated")],
    }
    if errors:
        result["errors"] = errors
    return result


def ask_clarification_node(state: AgentState) -> dict:
    """Ask for missing information instead of hallucinating.

    Generate ONE specific clarification question from the vague/incomplete query.
    If state["approval"] is a dict with approved is False, the question must reference
    the rejection reason and propose an alternative.

    CONTRACT:
    - MUST NOT return "route".
    - Set BOTH "pending_question" and "final_answer" (metric_from_state accepts either;
      setting both is the safe choice).
    - Event node name MUST be "clarify" (matches the graph node name).

    Return: {"pending_question": str, "final_answer": str, "events": [make_event("clarify", ...)]}
    """
    query = state.get("query", "")
    approval = state.get("approval")
    rejected = isinstance(approval, dict) and approval.get("approved") is False

    if rejected:
        comment = (approval or {}).get("comment") or "no reason provided"
        user_prompt = (
            f"User query:\n{query}\n\n"
            f"The proposed action was REJECTED.\n"
            f"Rejection reason: {comment}\n\n"
            "Write ONE clarification question that mentions the rejection reason and "
            "proposes a safer alternative the user can take."
        )
        fallback = (
            f"Your request was not approved ({comment}). "
            "Could you share more details or choose a safer alternative action?"
        )
    else:
        user_prompt = (
            f"User query:\n{query}\n\n"
            "The query is vague or missing key details. "
            "Write ONE specific clarification question to collect what is missing."
        )
        fallback = (
            "Could you provide more details about what you need help with "
            "(for example an order ID, account email, or the specific issue)?"
        )

    errors: list[str] = []
    try:
        llm = get_llm(temperature=0.0)
        response = llm.invoke(
            [
                {"role": "system", "content": CLARIFY_SYSTEM},
                {"role": "user", "content": user_prompt},
            ]
        )
        raw = getattr(response, "content", response)
        if isinstance(raw, list):
            raw = " ".join(
                block.get("text", str(block)) if isinstance(block, dict) else str(block)
                for block in raw
            )
        question = _safe_text(str(raw), fallback)
    except Exception as exc:  # noqa: BLE001 — node must not raise
        errors.append(f"ask_clarification_node LLM failure: {exc}")
        question = fallback

    result: dict = {
        "pending_question": question,
        "final_answer": question,
        "events": [make_event("clarify", "completed", "clarification requested")],
    }
    if errors:
        result["errors"] = errors
    return result
