"""Tool / reliability nodes — OWNER: M4.

Do not edit this file if you are not M4.
"""

from __future__ import annotations

import re

from .state import AgentState, make_event


def _extract_reference(query: str) -> str | None:
    """Pull an order/ticket/account-style reference id out of the query text."""
    match = re.search(r"\b\d{3,}\b", query)
    if match:
        return match.group(0)
    match = re.search(r"\b[A-Z]{2,}-?\d{2,}\b", query)
    if match:
        return match.group(0)
    return None


def tool_node(state: AgentState) -> dict:
    """Execute a mock tool call, simulating transient failure on the error route.

    CONTRACT:
    - Read "attempt" from state (retry_or_fallback_node has ALREADY incremented it
      before this node runs on a retry pass).
    - If state["route"] == "error" and attempt < 2 -> result string MUST contain "ERROR".
      Otherwise -> mock success string that quotes a fact from the query (order id, etc.).
    - "tool_results" has an `add` reducer: return a LIST with just the new item,
      never the whole accumulated list.
    - MUST NOT return "route".
    - Event node name MUST be "tool".

    Traced behaviour this produces (verify at Gate 2):
      S05 max_attempts=3: retry(a=1) -> tool ERROR -> retry(a=2) -> tool OK -> answer
      S07 max_attempts=1: retry(a=1) -> 1 < 1 is False -> dead_letter immediately

    Return: {"tool_results": [result_string], "events": [make_event("tool", ...)]}
    """
    route = state.get("route", "")
    attempt = state.get("attempt", 0)
    query = state.get("query", "")

    if route == "error" and attempt < 2:
        result = f"ERROR: transient tool failure on attempt {attempt} for query={query!r}"
        event = make_event(
            "tool", "failed", "tool call returned transient error", attempt=attempt
        )
        return {"tool_results": [result], "events": [event]}

    reference = _extract_reference(query)
    if reference:
        result = f"SUCCESS: lookup for reference {reference} completed"
    else:
        result = f"SUCCESS: mock tool result for query={query!r}"
    event = make_event("tool", "completed", "tool call succeeded", attempt=attempt)
    return {"tool_results": [result], "events": [event]}


def evaluate_node(state: AgentState) -> dict:
    """Evaluate the latest tool result — the retry-loop gate.

    Bonus: LLM-as-judge for result quality, with the `"ERROR" in result` heuristic
    as the fallback layer.

    CONTRACT:
    - "evaluation_result" MUST be exactly "success" or "needs_retry" — routing.py
      compares against these literals.
    - MUST NOT return "route".
    - Event node name MUST be "evaluate".

    Return: {"evaluation_result": str, "events": [make_event("evaluate", ...)]}
    """
    tool_results = state.get("tool_results") or []
    latest = tool_results[-1] if tool_results else ""

    if "ERROR" in latest:
        verdict = "needs_retry"
        message = "latest tool result reports an error, retry needed"
    else:
        verdict = "success"
        message = "latest tool result looks satisfactory"

    event = make_event("evaluate", "completed", message, verdict=verdict)
    return {"evaluation_result": verdict, "events": [event]}


def retry_or_fallback_node(state: AgentState) -> dict:
    """Record a retry attempt.

    CONTRACT:
    - Return attempt = state.get("attempt", 0) + 1.
    - Event node name MUST be exactly "retry" — metrics.py counts retries by
      `sum(1 for node in nodes if node == "retry")`. A different name = 0 retries.
    - Append one real message to "errors" (list reducer: return a 1-item list).
    - MUST NOT return "route".

    Return: {"attempt": int, "errors": [str], "events": [make_event("retry", ...)]}
    """
    attempt = state.get("attempt", 0) + 1
    max_attempts = state.get("max_attempts", 3)
    error_message = f"retry recorded: attempt {attempt}/{max_attempts}"

    event = make_event(
        "retry", "completed", error_message, attempt=attempt, max_attempts=max_attempts
    )
    return {"attempt": attempt, "errors": [error_message], "events": [event]}


def dead_letter_node(state: AgentState) -> dict:
    """Handle unresolvable failures after max retries exceeded.

    CONTRACT:
    - MUST NOT return "route" — S07's expected_route is "error", so overwriting
      route with "dead_letter" would fail the scenario.
    - "final_answer" explains N attempts were made and the request was escalated
      to a human queue.
    - Event node name MUST be "dead_letter".

    Return: {"final_answer": str, "events": [make_event("dead_letter", ...)]}
    """
    attempt = state.get("attempt", 0)
    max_attempts = state.get("max_attempts", 3)

    answer = (
        "We were unable to complete this request after "
        f"{attempt} attempt(s) (limit: {max_attempts}). This has been escalated to a "
        "human agent who will follow up."
    )
    event = make_event(
        "dead_letter", "exhausted", "max retries exceeded, escalating",
        attempt=attempt, max_attempts=max_attempts,
    )
    return {"final_answer": answer, "events": [event]}
