"""Classification node -- OWNER: M2.

Do not edit this file if you are not M2.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from .llm import get_llm
from .state import AgentState, make_event

_SYSTEM_PROMPT = """You are the intent classifier for a customer-support agent. \
Read the user's query and classify it into exactly one route.

Routes, in priority order (if a query could match more than one, pick the HIGHEST \
priority route that applies):

1. "risky" -- the action has a side effect on the customer's account or money: \
refunds, deletions, cancellations, sending emails, account changes.
   Example: "Refund this customer and send confirmation email" -> risky, risk_level=high
   Example: "Delete customer account after support verification" -> risky, risk_level=high

2. "tool" -- the user wants a lookup that needs an external system: order status, \
tracking, account balance, search.
   Example: "Please lookup order status for order 12345" -> tool, risk_level=low
   Example: "lookup order 12345" -> tool, risk_level=low

3. "missing_info" -- the query is too vague to act on; you don't know what "it" refers \
to or what the user actually wants. This includes short complaints that use a vague \
pronoun ("it", "this", "that") without naming what system, order, or feature is affected \
-- you cannot route the failure to a specific tool without asking what "it" is.
   Example: "Can you fix it?" -> missing_info, risk_level=low
   Example: "fix it" -> missing_info, risk_level=low
   Example: "It's broken" -> missing_info, risk_level=low (broken WHAT? no system named)

4. "error" -- the user reports a failure and NAMES the failing system, action, or \
process clearly enough to act on (retry/escalate) without asking a follow-up question.
   Example: "Timeout failure while processing request" -> error, risk_level=low
   Example: "System failure cannot recover after multiple attempts" -> error, risk_level=low
   Example: "Payment service unavailable, checkout keeps failing" -> error, risk_level=low

5. "simple" -- a general question answerable directly, with no tool call, no side \
effect, and no missing context.
   Example: "How do I reset my password?" -> simple, risk_level=low
   Example: "How to reset password?" -> simple, risk_level=low

Never classify by matching the exact wording of these examples -- reason about the \
intent of the actual query you receive. Set risk_level to "high" only for route \
"risky"; use "low" for every other route."""


class Classification(BaseModel):
    """Structured output contract for classify_node -- see CONTRACT.md rule 1."""

    route: Literal["simple", "tool", "missing_info", "risky", "error"] = Field(
        description="Exactly one of: simple, tool, missing_info, risky, error"
    )
    risk_level: Literal["low", "high"] = Field(
        description='"high" only when route == "risky", otherwise "low"'
    )
    reason: str = Field(description="One short sentence justifying the route")


def classify_node(state: AgentState) -> dict:
    """Classify the query into a route using an LLM.

    *** MUST use a real LLM call -- keyword-only heuristics will lose up to 15 points. ***
    *** MUST use .with_structured_output() -- regex/text parsing breaks hidden scenarios. ***

    CONTRACT:
    - This is the ONLY node allowed to return "route".
    - "route" MUST be one of exactly: "simple" | "tool" | "missing_info" | "risky" | "error"
    - "risk_level" is "high" for risky, "low" otherwise.
    - Priority guide for the prompt: risky > tool > missing_info > error > simple
    - NEVER branch on scenario_id or scenario wording.
    - Wrapped in try/except: on failure return route "simple" + an entry in "errors".
    """
    query = state.get("query", "")

    try:
        llm = get_llm()
        classifier = llm.with_structured_output(Classification)
        result: Classification = classifier.invoke(
            [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": query},
            ]
        )
        return {
            "route": result.route,
            "risk_level": result.risk_level,
            "events": [
                make_event("classify", "completed", result.reason, route=result.route)
            ],
        }
    except Exception as exc:  # noqa: BLE001 -- a raising node kills the whole graph run
        return {
            "route": "simple",
            "risk_level": "low",
            "errors": [f"classify_node fallback ({type(exc).__name__}): {exc}"],
            "events": [make_event("classify", "error_fallback", str(exc))],
        }
