"""Human-in-the-loop nodes — OWNER: M5.

Do not edit this file if you are not M5.
"""

from __future__ import annotations

import os

from .state import AgentState, ApprovalDecision, make_event


def risky_action_node(state: AgentState) -> dict:
    """Prepare a risky action for human approval.

    Describe the proposed action and why it requires approval.

    CONTRACT:
    - MUST NOT return "route" (S04/S06 expected_route is "risky").
    - Event node name MUST be "risky_action".

    Return: {"proposed_action": str, "events": [make_event("risky_action", ...)]}
    """
    query = state.get("query", "")
    proposed_action = f"Execute action requested by user for query: {query!r}. Requires human approval due to risk_level={state.get('risk_level', 'unknown')}."
    return {
        "proposed_action": proposed_action,
        "events": [
            make_event(
                "risky_action",
                "completed",
                "proposed action prepared for approval",
            )
        ],
    }


def approval_node(state: AgentState) -> dict:
    """Human-in-the-loop approval step.

    Default: mock approval (approved=True) so tests and CI run offline.
    Extension: if env LANGGRAPH_INTERRUPT=true, use langgraph.types.interrupt().

    CONTRACT:
    - "approval" MUST be a plain dict, NOT an ApprovalDecision instance.
      Use ApprovalDecision(...).model_dump(). routing.route_after_approval does
      state["approval"]["approved"], and metrics serializes state to JSON.
    - "approval" must never be None on this path — metrics.approval_observed is
      `approval is not None`, and S04/S06 need approval_observed=True.
    - Event node name MUST be exactly "approval" — metrics counts interrupts by
      `sum(1 for node in nodes if node == "approval")`. Gate 2 needs >= 2.
    - MUST NOT return "route".

    Return: {"approval": {"approved": bool, "reviewer": str, "comment": str},
             "events": [make_event("approval", ...)]}
    """
    try:
        if os.environ.get("LANGGRAPH_INTERRUPT", "").lower() == "true":
            from langgraph.types import interrupt

            payload = interrupt(
                {
                    "proposed_action": state.get("proposed_action", ""),
                    "question": "Approve this action?",
                }
            )
            if isinstance(payload, dict):
                decision = ApprovalDecision(
                    approved=bool(payload.get("approved", True)),
                    reviewer=str(payload.get("reviewer", "human-reviewer")),
                    comment=str(payload.get("comment", "")),
                )
            else:
                decision = ApprovalDecision(approved=True, reviewer="human-reviewer", comment="")
        else:
            decision = ApprovalDecision(
                approved=True,
                reviewer="mock-reviewer",
                comment="auto-approved (LANGGRAPH_INTERRUPT not set)",
            )
    except Exception as exc:  # noqa: BLE001 — node must never raise (but let GraphInterrupt propagate)
        from langgraph.errors import GraphInterrupt

        if isinstance(exc, GraphInterrupt):
            raise
        decision = ApprovalDecision(
            approved=True,
            reviewer="mock-reviewer",
            comment=f"fallback approval after error: {exc}",
        )

    return {
        "approval": decision.model_dump(),
        "events": [make_event("approval", "completed", "approval decision recorded")],
    }
